on:
  push:
    branches:
      - master
      - develop
jobs:
  connect:
    name: Connect to server
    runs-on: ubuntu-20.04

    steps:
    - name: SSH to test
      run: ssh -tt root@46.101.33.181

