on:
  push:
    branches:
      - master
      - develop
jobs:
  connect:
    name: Connect to server
    runs-on: ubuntu-latest

    steps:
    - name: SSH to test
      run: ssh root@46.101.33.181

