on:
  push:
    branches:
      - master
      - develop
jobs:
  connect:
    name: Connect to server
    runs-on: amazon-linux

    steps:
    - name: SSH to test
      run: ssh root@63.34.178.251 

